title:             Steven Nata Square Zero
email:             sssurajsuraj@gmail.com
description:       IMPLANTACION DE APLICACIONES WEB | JEKYLL
author:            Steven Nata
#url:               "localhost:4000"
url:               "https://waarven.github.io/"
baseurl:

# Social Profiles
#twitter_username:  SBootstrap
#github_username:   BlackrockDigital
#facebook_username: StartBootstrap

# Build settings
markdown:          kramdown
paginate:          4
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
