title:             Square Zero
email:             sssurajsuraj@gmail.com
description:       Silent Observations
author:            J
#url:               "localhost:4000"
url:               "http://squarezero.github.io/"
baseurl:

# Social Profiles
#twitter_username:  SBootstrap
#github_username:   BlackrockDigital
#facebook_username: StartBootstrap

# Build settings
markdown:          kramdown
paginate:          4
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
